"""
Collects and analyzes route information for documentation generation.

This module extracts metadata from registered routes including paths, methods,
parameters from docstrings, and statistics. The collected data is used to
generate the API documentation page (/docs endpoint).
"""

import inspect
from typing import Dict, List, Any, Optional
from pathlib import Path
import re

from ..types import RouteInfo
from ..core.registry import RouteRegistry


class DocsCollector:
    """
    Collects metadata about routes for documentation generation.
    
    This class analyzes all registered routes and extracts:
    - Route paths and HTTP methods
    - Handler function names and source files
    - Docstring content (descriptions, parameters, return values)
    - Route statistics (counts by method, dynamic vs static)
    - Route grouping by base path
    
    The collected data is structured for easy consumption by the documentation
    renderer.
    """
    
    def __init__(self, registry: RouteRegistry):
        """
        Initialize the documentation collector with a route registry.
        
        Args:
            registry: RouteRegistry containing all registered routes
        """
        self.registry = registry
        self.docs_data = {}
    
    def collect_all(self) -> Dict[str, Any]:
        """
        Collect all documentation data from registered routes.
        
        Returns:
            Dictionary containing:
            - info: Project information (name, version, config)
            - routes: List of route documentation dictionaries
            - groups: Routes grouped by base path
            - statistics: Route statistics (counts by method, etc.)
        """
        routes = self.registry.get_all()
        
        docs = {
            "info": self._get_project_info(),
            "routes": [],
            "groups": self._group_routes(routes),
            "statistics": self._get_statistics(routes),
        }
        
        for route in routes:
            route_doc = self._collect_route_doc(route)
            docs["routes"].append(route_doc)
        
        return docs
    
    def _get_project_info(self) -> Dict[str, Any]:
        """
        Get project information from configuration.
        
        Returns:
            Dictionary with project metadata including name, version,
            debug status, and CORS settings.
        """
        from ..config.loader import ConfigLoader
        config = ConfigLoader.load()
        
        return {
            "name": config.app_name,
            "version": self._get_version(),
            "description": "API documentation generated by FastAPI Route",
            "debug": config.debug,
            "cors_enabled": config.cors_enabled,
        }
    
    def _get_version(self) -> str:
        """
        Get FastAPI Route package version.
        
        Returns:
            Version string (e.g., "0.1.1") or "0.1.1" if version cannot be read
        """
        try:
            from ..version import __version__
            return __version__
        except ImportError:
            return "0.1.1"
    
    def _collect_route_doc(self, route: RouteInfo) -> Dict[str, Any]:
        """
        Collect documentation for a single route.
        
        Extracts:
        - Path and HTTP method
        - Handler function name and source file
        - Docstring content
        - Parameters from both path and docstring
        - Return value information from docstring
        
        Args:
            route: RouteInfo object to document
            
        Returns:
            Dictionary containing all route documentation metadata
        """
        docstring = inspect.getdoc(route.handler) or ""
        
        params = self._parse_params(docstring, route)
        returns = self._parse_returns(docstring)
        
        return {
            "path": route.path,
            "method": route.method,
            "handler_name": route.handler.__name__,
            "file_path": str(route.file_path),
            "docstring": docstring,
            "parameters": params,
            "returns": returns,
            "is_dynamic": route.is_dynamic,
            "param_names": route.param_names,
            "signature": str(inspect.signature(route.handler)),
        }
    
    def _parse_params(self, docstring: str, route: RouteInfo) -> List[Dict[str, Any]]:
        """
        Parse parameter information from docstring and route definition.
        
        Extracts:
        - Path parameters (from route.param_names)
        - Query parameters (from :param tags in docstring)
        
        Args:
            docstring: Handler function docstring
            route: RouteInfo object with parameter information
            
        Returns:
            List of parameter dictionaries with name, type, required, description
        """
        params = []
        
        # Add path parameters from route definition
        for param_name in route.param_names:
            params.append({
                "name": param_name,
                "type": "path",
                "required": True,
                "description": f"Path parameter: {param_name}",
                "example": f"example_{param_name}",
            })
        
        # Parse :param tags from docstring
        param_pattern = r":param\s+(\w+):\s*(.+?)(?=\n:|$)"
        matches = re.findall(param_pattern, docstring, re.DOTALL)
        
        for param_name, description in matches:
            # Determine if this is a path or query parameter
            param_type = "query"
            if param_name in route.param_names:
                param_type = "path"
            
            # Update existing parameter or add new one
            existing = next((p for p in params if p["name"] == param_name), None)
            if existing:
                existing["description"] = description.strip()
            else:
                params.append({
                    "name": param_name,
                    "type": param_type,
                    "required": param_type == "path",
                    "description": description.strip(),
                    "example": None,
                })
        
        return params
    
    def _parse_returns(self, docstring: str) -> Optional[Dict[str, Any]]:
        """
        Parse return value information from docstring.
        
        Args:
            docstring: Handler function docstring
            
        Returns:
            Dictionary with return description and type, or None if no :return tag
        """
        return_pattern = r":return:\s*(.+?)(?=\n:|$)"
        match = re.search(return_pattern, docstring, re.DOTALL)
        
        if match:
            return {
                "description": match.group(1).strip(),
                "type": "JSON",
            }
        return None
    
    def _group_routes(self, routes: List[RouteInfo]) -> Dict[str, List[Dict[str, Any]]]:
        """
        Group routes by their base path (first segment).
        
        For example:
        - /users/profile and /users/123 go to "users" group
        - /about and / go to "root" group
        
        Args:
            routes: List of RouteInfo objects
            
        Returns:
            Dictionary mapping group names to lists of route summaries
        """
        groups = {}
        
        for route in routes:
            # Extract first path segment (or "root" for root path)
            parts = route.path.strip("/").split("/")
            group = parts[0] if parts and parts[0] else "root"
            
            if group not in groups:
                groups[group] = []
            
            groups[group].append({
                "path": route.path,
                "method": route.method,
                "description": inspect.getdoc(route.handler) or "",
            })
        
        return groups
    
    def _get_statistics(self, routes: List[RouteInfo]) -> Dict[str, Any]:
        """
        Generate statistics about the route collection.
        
        Calculates:
        - Total number of routes
        - Count of dynamic routes (with path parameters)
        - Count of static routes (without parameters)
        - Distribution of HTTP methods
        
        Args:
            routes: List of RouteInfo objects
            
        Returns:
            Dictionary with route statistics
        """
        methods = {}
        dynamic_count = 0
        
        for route in routes:
            method = route.method
            methods[method] = methods.get(method, 0) + 1
            if route.is_dynamic:
                dynamic_count += 1
        
        return {
            "total_routes": len(routes),
            "dynamic_routes": dynamic_count,
            "static_routes": len(routes) - dynamic_count,
            "methods": methods,
        }